name: sketch_agent
channels:
  - conda-forge
  - defaults
dependencies:
#  - _libgcc_mutex=0.1
#  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
#  - ld_impl_linux-64=2.43
  - gfortran_impl_osx-arm64
  - libffi=3.4.2
  - libgcc-amzn2-aarch64
  - llvm-openmp
#  - libgcc=14.2.0
#  - libgcc-ng=14.2.0
#  - libgomp=14.2.0
#  - libnsl=2.0.1
  - libsqlite=3.47.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - mypy_extensions=1.0.0
  - ncurses=6.5
  - openssl=3.4.0
  - pip=22.3.1
  - pycparser=2.21
  - pyre-extensions=0.0.29
  - python=3.8.19
  - readline=8.2
  - setuptools=68.2.2
  - tk=8.6.13
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_inspect=0.9.0
  - wheel=0.45.1
  - xz=5.2.6
  - pip:
    - annotated-types==0.7.0
    - anthropic==0.36.0
    - openai
    - anyio==4.5.2
    - blinker==1.8.2
    - cairo
    - cairocffi==1.6.1
    - cairosvg==2.7.1
    - certifi==2024.8.30
    - cffi==1.17.1
    - charset-normalizer==3.4.0
    - click==8.1.7
    - cssselect2==0.7.0
    - defusedxml==0.7.1
    - distro==1.9.0
    - exceptiongroup==1.2.2
    - filelock==3.16.1
    - flask==3.0.3
    - fsspec==2024.10.0
    - h11==0.14.0
    - httpcore==1.0.7
    - httpx==0.27.2
    - huggingface-hub==0.26.2
    - idna==3.10
    - imageio==2.35.1
    - importlib-metadata==8.5.0
    - itsdangerous==2.2.0
    - jinja2==3.1.4
    - jiter==0.7.1
    - joblib==1.4.2
    - lazy-loader==0.4
    - markupsafe==2.1.5
    - networkx==3.1
    - numpy==1.24.4
    - packaging==24.2
    - pillow==10.3.0
    - pydantic==2.10.1
    - pydantic-core==2.27.1
    - python-dotenv==1.0.1
    - pywavelets==1.4.1
    - pyyaml==6.0.2
    - requests==2.32.3
    - scikit-image==0.20.0
    - scikit-learn==1.3.2
    - scipy==1.9.1
    - sniffio==1.3.1
    - svgpathtools==1.6.1
    - svgwrite==1.4.3
    - threadpoolctl==3.5.0
    - tifffile==2023.7.10
    - tinycss2==1.4.0
    - tokenizers==0.20.3
    - tqdm==4.67.1
    - urllib3==2.2.3
    - webencodings==0.5.1
    - werkzeug==3.0.6
    - zipp==3.20.2